### ISSUE TITLE
[NEWDOMAIN] New domain to unlock

### ISSUE THREAD

**Issue by captainhook** [gioxx/fxaddons#1]
[ENG/ITA]

**New domain to unlock** / **Nuovo dominio da sbloccare**
https://thecreative.cafe

**Comment by gioxx** [comment]
https://github.com/gioxx/fxaddons/commit/83325b5fe6688bfabff4bda20a738befe4c13d91
Il componente aggiuntivo verrà aggiornato anche su Addons.mozilla.org.
This addon will be updated also on Addons.mozilla.org
