### ISSUE TITLE
[NEWDOMAIN] writingcoooperative.com

### ISSUE THREAD

**Issue by alizehctl** [gioxx/fxaddons#3]
**New domain to unlock** / **Nuovo dominio da sbloccare**
I was trying to read this article today and noticed Medium Unlimited wasn't working. Would be nice to have this domain added:

Example article: 
https://writingcooperative.com/zettelkasten-how-one-german-scholar-was-so-freakishly-productive-997e4e0ca125

**Comment by gioxx** [comment]
All done, just wait the automatic update from addons.mozilla.org :-)
Giovanni.

**Comment by alizehctl** [comment]
@gioxx thanks for the prompt response!
